"""Sector and objective pages (Solutions). One data entry per page, one shared layout."""


def scen(label, credits, brief, intro, prod, picks_intro, picks, choice, gen_text, res, publish, meta_intro, meta):
    steps = [{'u': brief}]
    if prod:
        steps.append({'a': intro, 'card': dict(t='prod', **prod)})
        steps.append({'a': picks_intro, 'card': {'t': 'picks', 'list': picks, 'pick': 0}})
    else:
        steps.append({'a': intro + ' ' + picks_intro, 'card': {'t': 'picks', 'list': picks, 'pick': 0}})
    steps += [{'u': choice}, {'a': gen_text, 'card': {'t': 'gen', 'cost': 300 if prod else 280}},
              {'a': 'Ta vidéo est prête :' if 'img' not in res else 'Voilà ta vidéo et le visuel :', 'card': dict(t='res', **res)},
              {'u': publish}, {'a': meta_intro, 'card': dict(t='meta', **meta)}]
    return {'label': label, 'credits': credits, 'steps': steps}


SECTORS = {
  'beaute-cosmetique': dict(
    meta=("Growthity pour la beauté et la cosmétique", "Des vidéos UGC beauté qui montrent la texture et le résultat : tutos, avant / après et routines générés par l'IA, publiés sur Meta."),
    pill='Beauté & cosmétique', h=('Des pubs beauté', 'qui font vraies.'),
    lede="Textures, swatches, routines, avant / après : Growthity crée des vidéos où une créatrice applique votre produit comme une vraie cliente, et les publie sur Instagram et Facebook.",
    scen=scen('Beauté', 7240, "Je lance un gloss repulpant sur ma boutique. Je veux une vidéo qui montre la texture, pas une pub de magazine.",
              "Bonne idée : un tuto express face caméra, gros plan sur la texture et l'effet brillant. J'ai importé ton produit :",
              dict(img='gloss-lips', name='Gloss Repulpant · Rose nude', sub='Importé depuis ta boutique · 6 photos'),
              "Voici 3 créatrices beauté crédibles :", [['real-42', 'Camille'], ['lena-serum', 'Léna'], ['ugc-solaire', 'Sarah']],
              "Camille. Accroche : la tenue toute la journée.", "Je génère la vidéo 9:16 avec un plan produit inséré au milieu.",
              dict(video='real-42', words=['Ce gloss', 'tient <em>vraiment</em>', 'toute la journée'], img='gloss-lips.webp'),
              "Publie sur Meta : France, femmes 18-35 ans, 25 € par jour, objectif ventes.", "C'est en ligne. Aperçu de ta pub :",
              dict(aud=['France', 'Femmes 18–35 ans', 'Placements auto', '25 € / jour', 'Ventes'], brand='Lumi Beauty', site='lumi-beauty.fr', logo='lumi', video='real-42',
                   text="Testé du café du matin au dîner : il n'a pas bougé. Et zéro effet collant 💋", headline='Gloss Repulpant · Rose nude', cta='Acheter',
                   m=[['Impressions', 21300], ['Clics', 640], ['Ventes', 41]])),
    hooks=[('Démonstration', 'Regardez la texture en gros plan.', "La beauté s'achète avec les yeux : montrer le produit sur la peau rassure plus qu'une promesse."),
           ('Avant / après', '3 semaines, zéro fond de teint.', "Un résultat concret et daté, raconté par quelqu'un qui ressemble à la cliente."),
           ('Routine', 'Ma routine du matin en 30 secondes.', "Le format routine montre le produit en situation et mène naturellement à l'achat.")],
    pains=('2 000 €', ["Envoyer des produits à des influenceuses et attendre", "Payer un shooting pour chaque teinte", "Des visuels trop « pub » que personne ne regarde", "Ne pas savoir quelle vidéo a fait vendre"],
           '2 minutes', ["Une créatrice UGC qui tient votre produit", "Toutes vos teintes déclinées en un brief", "Des tutos et des avant / après qui font vrais", "Ventes et retour sur pub suivis par campagne"]),
    uses=['Skincare', 'Maquillage', 'Soins capillaires', 'Parfums', 'Ongles', 'Cosmétique bio', 'Soins homme', 'Instituts'],
    bento=[('eye', 'pink', 'Le produit sur la peau', "Textures, swatches, application : les créatrices montrent le produit comme le ferait une cliente."),
           ('layers', 'orange', 'Toutes vos teintes', "Une vidéo, puis ses déclinaisons pour chaque teinte ou parfum, sans nouveau tournage."),
           ('text', 'indigo', 'Sous-titres et mots-clés', "Les bénéfices clés s'affichent en gros, pour les vidéos regardées sans le son."),
           ('search', 'slate', 'Ce que font les marques qui cartonnent', "L'Espion Meta Ads vous montre les pubs beauté qui tournent depuis des semaines."),
           ('euro', 'green', 'Ventes suivies', "Ventes, revenu généré et retour sur pub par campagne, directement depuis vos données Meta."),
           ('refresh', 'blue', 'Toujours de nouvelles créas', "En beauté, les pubs s'usent vite : déclinez la gagnante avant qu'elle ne s'essouffle.")],
    md=['real-42', 'ugc-solaire'],
    faq=[("Les créatrices peuvent-elles appliquer mon produit ?", "Oui : l'acteur tient, montre et applique votre produit dans la scène, comme dans un vrai tuto."),
         ("Et les promesses de résultat ?", "Le chat formule les bénéfices de façon mesurée, et vous validez chaque texte avant publication.")],
    rel=['acteurs-ugc', 'creations-catalogue', 'espion-meta-ads']),

  'maison-deco': dict(
    meta=("Growthity pour la maison, la déco et l'entretien", "Des pubs qui mettent vos produits en scène chez vos clients : vidéos UGC, visuels et carrousels de collection, publiés sur Meta."),
    pill='Maison & entretien', h=('Vos produits,', 'chez vos clients.'),
    lede="Bougies, linge, produits ménagers, déco : Growthity met vos produits en scène dans de vrais intérieurs, avec des créatrices qui les utilisent, et les publie sur Meta.",
    scen=scen('Maison', 6180, "Je vends un parfum de linge naturel. Je veux une vidéo qui donne l'impression de sentir le linge propre.",
              "Je pars sur une scène du quotidien à la maison, ton naturel, le flacon bien visible. Ton produit :",
              dict(img='lessive-bottle', name='Parfum de linge · Fleur de coton', sub='Importé depuis ton site · 8 photos'),
              "3 profils qui collent à ton univers :", [['real-05', 'Clara'], ['real-19', 'Julie'], ['ugc-femme', 'Léa']],
              "Clara, à la maison. Accroche sur la durée du parfum.", "Génération : vidéo 9:16 et un visuel 4:5 du linge.",
              dict(video='real-05', words=['Un linge', 'qui sent bon', '<em>3 semaines</em>'], img='lessive-linge.webp'),
              "Publie : France, 25-55 ans, 20 € par jour, objectif ventes.", "C'est en ligne. Aperçu de ta pub :",
              dict(aud=['France', '25–55 ans', 'Tous genres', '20 € / jour', 'Ventes'], brand='Lessiva', site='lessiva.fr', logo='lessiva', video='real-05',
                   text="Mon linge sent encore bon 3 semaines après. Et c'est d'origine naturelle 🌿", headline='Parfum de linge · Fleur de coton', cta='Acheter',
                   m=[['Impressions', 16800], ['Clics', 455], ['Ventes', 29]])),
    hooks=[('Sensoriel', "Vous sentez ce linge à travers l'écran ?", "Faire imaginer une odeur ou une texture donne plus envie qu'une liste d'ingrédients."),
           ('Comparaison', "J'ai remplacé mon assouplissant par ça.", "Le « avant / maintenant » parle à ceux qui utilisent déjà un produit concurrent."),
           ('Idée cadeau', "Le cadeau qu'on n'attend pas et qu'on adore.", "À l'approche des fêtes, l'angle cadeau multiplie les achats d'impulsion.")],
    pains=('4 semaines', ["Shooter chaque produit en studio", "Des photos parfaites mais sans émotion", "Une seule vidéo pour toute la saison", "Des pubs qui s'usent sans qu'on le voie"],
           '2 minutes', ["Des scènes du quotidien qui donnent envie", "Vidéo, visuel et carrousel en un brief", "Un angle par saison : rentrée, fêtes, été", "Le pilotage IA repère les pubs qui s'essoufflent"]),
    uses=["Bougies & parfums d'intérieur", 'Produits ménagers', 'Linge de maison', 'Déco', 'Mobilier', 'Cuisine', 'Jardin', 'Literie'],
    bento=[('home', 'orange', 'Votre produit chez vos clients', "Une cuisine, un salon, une buanderie : vos produits mis en scène là où ils servent vraiment."),
           ('copy', 'pink', 'Carrousels de collection', "Toute une gamme présentée en un carrousel, généré à partir de vos photos."),
           ('calendar', 'indigo', 'Un angle par saison', "Rentrée, fêtes, soldes, été : le même produit, l'ambiance du moment."),
           ('grid', 'green', 'Toute la boutique en lot', "Collez votre site : Growthity produit un lot de créas pour vos best-sellers."),
           ('chart', 'blue', 'Fatigue créative surveillée', "Growthity vous prévient quand une pub est trop vue et propose la suite."),
           ('euro', 'slate', '0 % de commission', "Votre budget pub reste sur votre compte Meta, sans frais sur vos dépenses.")],
    md=['real-05', 'bougie-916'],
    faq=[("Mes photos produit suffisent-elles ?", "Oui. Vos photos servent de base aux visuels et aux vidéos ; Growthity peut aussi les récupérer sur votre site."),
         ("Puis-je préparer mes pubs de Noël à l'avance ?", "Oui : demandez un angle saisonnier au chat, gardez les créas dans un dossier et publiez-les quand vous voulez.")],
    rel=['studio-en-lot', 'formats', 'pilotage-ia']),

  'restauration': dict(
    meta=("Growthity pour les restaurants", "Des vidéos qui donnent faim, diffusées seulement autour de votre restaurant : plus de réservations et de commandes, sans photographe."),
    pill='Restauration', h=('Des pubs qui donnent faim,', 'autour de chez vous.'),
    lede="Le plat, la salle, l'ambiance : Growthity crée des vidéos qui donnent envie de réserver ce soir, et les diffuse dans votre département, auprès des gens qui peuvent venir.",
    scen=scen('Restaurant', 3950, "J'ai un restaurant à Lyon. Je veux remplir la salle en semaine, surtout le midi.",
              "On va montrer l'expérience à table, ton chaleureux, et cibler les gens qui travaillent autour.", None,
              "Voici 3 profils :", [['real-04', 'Nina'], ['ugc-femme', 'Léa'], ['actor-thomas', 'Thomas']],
              "Nina, parfait. Mets en avant la commande depuis la table.", "Je génère la vidéo 9:16 : Nina à table, commande en deux clics.",
              dict(video='real-04', words=['Commandé', 'depuis', '<em>ma table</em>']),
              "Publie : département du Rhône, 22-50 ans, 15 € par jour, bouton Réserver vers mon site.", "C'est en ligne. Aperçu de ta pub :",
              dict(aud=['Rhône (69)', '22–50 ans', 'Tous genres', '15 € / jour', 'Trafic'], brand='Le Comptoir', site='lecomptoir-lyon.fr', logo='comptoir', video='real-04',
                   text="Le midi, on commande depuis la table et on est servi en 12 minutes. Réservez votre place 👇", headline='Déjeuner au Comptoir', cta='Réserver',
                   m=[['Impressions', 9400], ['Clics', 318], ['Visites du site', 271]])),
    hooks=[('Le plat', 'Ce plat-là, on revient pour lui.', "Un plat signature filmé de près donne faim instantanément."),
           ("L'expérience", 'Servi en 12 minutes, même le midi.', "Le midi, le temps est l'argument numéro un."),
           ("L'offre", 'Le dessert offert sur présentation de cette pub.', "Une offre simple et locale déclenche la visite et se mesure facilement.")],
    pains=('Au hasard', ["Compter sur le bouche-à-oreille et les avis", "Payer un photographe à chaque nouvelle carte", "Booster des posts sans savoir à qui", "Ne pas savoir si la pub a rempli la salle"],
           'Salle pleine', ["Une vidéo qui donne faim, en quelques minutes", "Une pub par nouveauté : plat du jour, brunch, soirée", "Diffusée seulement dans votre département", "Réservations suivies pub par pub"]),
    uses=['Restaurants', 'Brasseries', 'Bars', 'Boulangeries', 'Food trucks', 'Dark kitchens', 'Traiteurs', 'Salons de thé'],
    bento=[('utensils', 'orange', 'Votre cuisine en vidéo', "Le plat, la salle, l'ambiance : des vidéos qui donnent envie de réserver ce soir."),
           ('pin', 'blue', 'Votre département', "Incluez votre département, excluez les autres : vous payez pour des clients qui peuvent venir."),
           ('calendar', 'green', 'Réserver, Commander, Contacter', "Le bouton de la pub mène à votre page de réservation, de commande ou à votre site."),
           ('refresh', 'pink', 'Une pub par nouveauté', "Nouvelle carte, brunch du dimanche, soirée spéciale : une pub prête en quelques minutes."),
           ('euro', 'indigo', 'Petit budget, vrai résultat', "Pour un quartier, 10 à 20 € par jour suffisent souvent."),
           ('store', 'slate', 'Plusieurs adresses ?', "Une campagne par établissement, chacune ciblée sur son quartier.")],
    md=['real-04', 'real-04-hd'],
    faq=[("Quel budget pour un restaurant ?", "Pour un quartier ou une petite ville, 10 à 20 € par jour suffisent souvent pour être vu chaque semaine par les habitants et ceux qui travaillent autour."),
         ("Puis-je promouvoir une offre ponctuelle ?", "Oui : brunch, menu de saison, soirée à thème. Dites-le au chat, la pub est prête en quelques minutes.")],
    rel=['commerce-local', 'publication-meta', 'franchises-reseaux']),

  'renovation-energie': dict(
    meta=("Growthity pour la rénovation et l'énergie", "Solaire, pompes à chaleur, isolation : des vidéos qui lèvent les objections et des formulaires qui qualifient, pour des demandes de devis exclusives."),
    pill='Rénovation & énergie', h=('Des demandes de devis,', 'rien qu\'à vous.'),
    lede="Solaire, pompes à chaleur, isolation, menuiseries : Growthity crée des vidéos qui lèvent les objections de vos prospects et publie des campagnes de devis sur votre zone d'intervention.",
    scen=scen('Rénovation', 5120, "Je pose des carports solaires en Gironde. Je veux des demandes de devis de propriétaires.",
              "L'angle qui marche : lever l'objection du prix, avec un témoignage d'installateur crédible.", None,
              "Voici 3 profils :", [['real-12', 'Hugo'], ['real-06', 'Chloé'], ['ugc-pac-awa', 'Awa']],
              "Hugo, devant une installation.", "Génération : vidéo 9:16 tournée en extérieur, sous-titres inclus.",
              dict(video='real-12', words=['Je pensais', "que c'était", '<em>trop cher</em>…']),
              "Publie : Gironde, 35-65 ans, 30 € par jour, formulaire de devis.", "Campagne de devis créée. Aperçu :",
              dict(aud=['Gironde (33)', '35–65 ans', 'Tous genres', '30 € / jour', 'Leads'], brand='Volta Solaire', site='volta-solaire.fr', logo='volta', video='real-12',
                   text="Je pensais qu'un carport solaire coûtait trop cher… jusqu'à ce que je fasse le calcul. Simulation gratuite en 2 minutes ☀️", headline='Carport solaire · Simulation gratuite', cta='Demander un devis',
                   m=[['Impressions', 12700], ['Clics', 356], ['Devis', 23]])),
    hooks=[('Objection prix', 'Je pensais que ça coûtait trop cher…', "Dire à voix haute le premier frein fait se reconnaître le prospect."),
           ('Économies', 'Ma facture a baissé de moitié cet hiver.', "Un chiffre concret et vécu vaut mieux qu'un pourcentage générique."),
           ('Financement', "Vos panneaux peuvent se financer avec l'électricité qu'ils produisent.", "Expliquer le financement débloque les propriétaires qui hésitent.")],
    pains=('Leads partagés', ["Acheter des leads revendus à plusieurs concurrents", "Des pubs génériques qui attirent des curieux", "Des formulaires sans qualification", "Des semaines pour tester un nouvel angle"],
           'Vos leads', ["Des leads exclusifs, venus de vos pubs", "Des témoignages qui lèvent les objections", "Des questions de qualification dans le formulaire", "Un nouvel angle testé dès demain"]),
    uses=['Panneaux solaires', 'Pompes à chaleur', 'Isolation', 'Menuiseries', 'Toiture', 'Chauffage', 'Bornes de recharge', 'Rénovation globale'],
    bento=[('bolt', 'green', 'Des leads qui vous appartiennent', "Vos formulaires Meta, vos contacts : pas de leads revendus à la concurrence."),
           ('target', 'blue', 'Formulaires qualifiants', "Propriétaire ? Type de logement ? Délai ? Vous ne rappelez que les bons projets."),
           ('pin', 'orange', "Votre zone d'intervention", "Départements à inclure ou à exclure : seulement là où vos équipes se déplacent."),
           ('chat', 'indigo', 'Les objections, traitées', "Prix, financement, délais, fiabilité : une vidéo par objection, à tester côte à côte."),
           ('chart', 'pink', 'Coût par devis suivi', "Le pilotage IA vous dit quelle vidéo ramène les devis les moins chers."),
           ('users', 'slate', 'Plusieurs agences ?', "Une campagne par agence, chacune sur sa zone, dans le même espace.")],
    md=['real-12', 'ugc-pac-awa'],
    faq=[("Les leads sont-ils exclusifs ?", "Oui. Ils viennent de vos propres pubs et de vos formulaires Meta : ils ne sont partagés avec personne."),
         ("Puis-je parler des aides et du financement ?", "Oui, en restant factuel. Le chat rédige des textes mesurés et vous validez chaque pub avant publication.")],
    rel=['leads-ventes', 'b2b-leads', 'franchises-reseaux']),

  'formation-coaching': dict(
    meta=("Growthity pour la formation et le coaching", "Remplissez vos ateliers, formations et sessions de coaching avec des vidéos témoignage, votre propre visage en acteur et des inscriptions suivies."),
    pill='Formation & coaching', h=('Remplissez vos sessions,', 'sans tourner.'),
    lede="Coachs, formateurs, consultants : Growthity crée des vidéos témoignage, ou des vidéos incarnées par vous depuis une simple photo, et des campagnes d'inscription sur Meta.",
    scen=scen('Coaching', 4410, "Je suis coach en prise de parole. Je veux remplir mon prochain atelier.",
              "Je propose un témoignage face caméra : la peur de parler en public, puis le déclic.", None,
              "Voici 3 profils :", [['real-14', 'Inès'], ['actor-claire', 'Claire'], ['ugc-femme', 'Léa']],
              "Inès, ton sincère.", "Génération : vidéo 9:16 face caméra, sous-titres inclus.",
              dict(video='real-14', words=['Trois séances', 'pour', '<em>oser parler</em>']),
              "Publie : France, 25-45 ans, 20 € par jour, formulaire d'inscription.", "C'est en ligne. Aperçu de ta pub :",
              dict(aud=['France', '25–45 ans', 'Tous genres', '20 € / jour', 'Leads'], brand='Mila Coaching', site='milacoaching.fr', logo='mila', video='real-14',
                   text="J'avais le cœur qui battait à chaque réunion. Trois séances plus tard, j'ai présenté devant 80 personnes.", headline='Atelier prise de parole · 12 places', cta="S'inscrire",
                   m=[['Impressions', 10200], ['Clics', 301], ['Inscriptions', 38]])),
    hooks=[('Transformation', "Il y a 3 mois, je n'osais pas parler en réunion.", "On n'achète pas une formation, on achète la personne qu'on va devenir."),
           ('Erreur fréquente', "L'erreur que je vois chez presque tous mes élèves.", "Pointer une erreur concrète prouve votre expertise en quelques secondes."),
           ('Places limitées', "Plus que 12 places pour l'atelier de mars.", "Une date et un nombre de places donnent une raison d'agir maintenant.")],
    pains=('Posts organiques', ["Publier tous les jours en espérant être vu", "Tourner soi-même ses vidéos, encore et encore", "Des webinaires à moitié vides", "Ne pas savoir quel message attire les bons élèves"],
           'Agenda plein', ["Des vidéos témoignage sans tournage", "Votre propre visage en acteur, depuis une photo", "Des inscriptions suivies pub par pub", "Les messages qui convertissent, repérés pour vous"]),
    uses=['Coachs', 'Formations en ligne', 'Organismes de formation', 'Consultants', 'Thérapeutes', 'Professeurs', 'Écoles', 'Auteurs'],
    bento=[('user', 'indigo', 'Votre visage, sans tournage', "Créez votre acteur depuis une photo : vos pubs sont incarnées par vous, en quelques minutes."),
           ('mic', 'pink', 'Des témoignages qui touchent', "Le déclic, la transformation, le résultat : les histoires qui donnent envie de s'inscrire."),
           ('calendar', 'green', 'Ateliers et webinaires', "Une pub par session, avec la date et le nombre de places."),
           ('target', 'blue', 'Leads et inscriptions', "Formulaire Meta ou page d'inscription : chaque inscrit relié à la pub qui l'a amené."),
           ('bulb', 'orange', 'Les angles de votre niche', "L'Espion Meta Ads vous montre ce qui marche chez les autres formateurs."),
           ('chart', 'slate', 'Coût par inscrit', "Le pilotage IA vous dit quel message remplit vos sessions au meilleur prix.")],
    md=['real-14', 'actor-zoe'],
    faq=[("Puis-je apparaître moi-même dans les pubs ?", "Oui. Créez votre acteur à partir d'une photo, il peut ensuite porter toutes vos vidéos."),
         ("Ça marche pour une formation à distance ?", "Oui : formation en ligne, atelier en présentiel, coaching individuel. L'objectif et le ciblage s'adaptent.")],
    rel=['acteurs-ugc', 'leads-ventes', 'guide-pub-ugc']),

  'immobilier': dict(
    meta=("Growthity pour l'immobilier", "Des demandes d'estimation et des mandats grâce à des vidéos incarnées par vos conseillers et des campagnes Meta sur votre secteur."),
    pill='Immobilier', h=('Des vendeurs,', 'pas des curieux.'),
    lede="Agences, mandataires, promoteurs : Growthity crée des vidéos incarnées par vos conseillers et des campagnes d'estimation sur votre secteur, pour rentrer des mandats.",
    scen=scen('Immobilier', 5630, "Agence immobilière à Bordeaux. Je veux des propriétaires qui veulent faire estimer leur bien.",
              "Le bon levier : une estimation gratuite, présentée par une conseillère de confiance.", None,
              "Voici 3 profils :", [['actor-claire', 'Claire'], ['actor-thomas', 'Thomas'], ['real-14', 'Inès']],
              "Claire, ton rassurant.", "Génération : vidéo 9:16, sous-titres inclus.",
              dict(video='actor-claire', words=['Combien vaut', '<em>votre bien</em>', "aujourd'hui ?"]),
              "Publie : Gironde, 30-65 ans, 25 € par jour, formulaire d'estimation.", "Campagne de leads créée. Aperçu :",
              dict(aud=['Gironde (33)', '30–65 ans', 'Tous genres', '25 € / jour', 'Leads'], brand='Rivage Immobilier', site='rivage-immo.fr', logo='rivage', color='#0F766E', video='actor-claire',
                   text="Les prix ont bougé dans votre quartier. Recevez l'estimation de votre bien sous 48 h, gratuitement et sans engagement.", headline='Estimation gratuite · Bordeaux', cta='En savoir plus',
                   m=[['Impressions', 8900], ['Clics', 247], ['Estimations', 19]])),
    hooks=[('Curiosité', "Combien vaut vraiment votre maison aujourd'hui ?", "Presque tous les propriétaires se posent la question : y répondre gratuitement ouvre la conversation."),
           ('Marché local', 'Les prix ont bougé dans votre quartier.', "Parler du quartier précis rend la pub immédiatement pertinente."),
           ('Visite', 'Une visite comme si vous y étiez.', "La visite filmée attire les acheteurs et montre votre savoir-faire aux vendeurs.")],
    pains=('Portails', ["Dépendre des portails et de leurs tarifs", "Distribuer des flyers sans savoir ce qu'ils rapportent", "Tourner soi-même des vidéos de biens", "Des contacts froids, rarement vendeurs"],
           'Mandats', ["Des propriétaires qui demandent une estimation", "Des vidéos pro sans caméra", "Des campagnes sur vos départements", "Chaque contact relié à la pub d'origine"]),
    uses=['Agences immobilières', 'Mandataires', 'Promoteurs', 'Gestion locative', 'Immobilier neuf', "Chasseurs d'appartements", 'Location saisonnière', 'Viager'],
    bento=[('key', 'blue', 'Des vendeurs, pas des curieux', "Formulaire d'estimation qualifiant : adresse, type de bien, projet, délai."),
           ('pin', 'orange', 'Votre secteur', "Une campagne par département, là où vous voulez rentrer des mandats."),
           ('user', 'indigo', "Votre équipe à l'écran", "Vos conseillers en acteurs, créés depuis une photo, pour des pubs incarnées."),
           ('home', 'green', 'Les biens en vidéo', "Vos exclusivités en visuels et en carrousels, générés depuis vos photos."),
           ('target', 'pink', 'Leads en direct', "Chaque demande d'estimation arrive dans Growthity, avec la pub qui l'a amenée."),
           ('chart', 'slate', 'Les contacts les plus sérieux', "Le pilotage IA vous dit quelle pub ramène les demandes qui aboutissent.")],
    md=['actor-claire', 'actor-thomas'],
    faq=[("Puis-je qualifier les demandes d'estimation ?", "Oui : le chat crée le formulaire Meta avec vos questions (type de bien, projet, délai). Une réponse disqualifiante passe automatiquement le lead en « Non qualifié »."),
         ("Mes conseillers peuvent-ils apparaître dans les pubs ?", "Oui : chacun peut devenir un acteur à partir d'une simple photo.")],
    rel=['leads-ventes', 'acteurs-ugc', 'commerce-local']),

  'tech-applis': dict(
    meta=("Growthity pour la tech et les applis", "Montrez votre produit en action : vidéos UGC de démonstration, une pub par fonctionnalité et des campagnes d'essai gratuit sur Meta."),
    pill='Tech & applis', h=('Votre produit en action,', 'pas en captures.'),
    lede="SaaS, applis, objets connectés : Growthity crée des vidéos où un utilisateur montre votre produit en situation, et lance des campagnes d'inscription ou d'essai gratuit.",
    scen=scen('Tech', 8020, "On a une appli qui aide les commerces à récolter des avis Google. Je veux des essais gratuits.",
              "Montrons le produit en action : une commerçante scanne le QR code, l'avis arrive.", None,
              "Voici 3 profils :", [['real-40', 'Emma'], ['actor-zoe', 'Zoé'], ['real-14', 'Inès']],
              "Emma, en boutique.", "Génération : vidéo 9:16 de démonstration, sous-titres inclus.",
              dict(video='real-40', words=['+38 avis', '<em>en un mois</em>', 'sans rien demander']),
              "Publie : France, mon audience enregistrée « Commerçants », 30 € par jour, vers la page d'essai.", "C'est en ligne. Aperçu de ta pub :",
              dict(aud=['France', '25–55 ans', 'Audience : Commerçants', '30 € / jour', 'Trafic'], brand='Avis Boost', site='avisboost.fr', logo='nails', video='real-40',
                   text="Mes clients laissaient rarement un avis. Avec un QR code sur le comptoir, j'en ai eu 38 en un mois.", headline='Essai gratuit 14 jours', cta='Essayer',
                   m=[['Impressions', 14300], ['Clics', 402], ['Visites', 351]])),
    hooks=[('Démo produit', "Regardez : je scanne, l'avis est publié.", "Montrer le produit marcher en 5 secondes vaut toutes les explications."),
           ('Problème', "Vos clients adorent, mais ne laissent jamais d'avis ?", "Nommer le problème exact fait se reconnaître la bonne cible."),
           ('Résultat', '38 avis en un mois, sans rien demander.', "Un résultat chiffré et vécu donne une raison concrète d'essayer.")],
    pains=('Captures', ["Expliquer un logiciel avec des captures d'écran", "Refaire les vidéos produit à chaque mise à jour", "Des essais gratuits qui ne viennent pas", "Un coût d'acquisition découvert trop tard"],
           'Essais', ["Le produit montré en situation réelle", "Une nouvelle vidéo à chaque fonctionnalité", "Des campagnes d'inscription à l'essai", "Le coût par essai suivi pub par pub"]),
    uses=['SaaS', 'Applis mobiles', 'Logiciels pour pros', 'Objets connectés', 'Fintech', 'Marketplaces', 'Outils no-code', 'Jeux'],
    bento=[('phone', 'cyan', 'Votre produit en situation', "Un utilisateur qui montre l'appli ou l'objet en action, plutôt qu'une capture d'écran."),
           ('play', 'pink', 'Une vidéo par fonctionnalité', "Chaque nouveauté mérite sa pub : elle est prête en quelques minutes."),
           ('target', 'green', 'Inscriptions et essais', "Objectif essai gratuit ou démo, avec chaque inscription reliée à sa pub."),
           ('users', 'indigo', 'B2C comme B2B', "Ciblez les particuliers, les commerçants ou les décideurs selon votre produit."),
           ('search', 'slate', 'Veille concurrentielle', "L'Espion Meta Ads vous montre les pubs des autres applis de votre catégorie."),
           ('chart', 'blue', "Coût d'acquisition en clair", "Le pilotage IA suit le coût par essai et vous dit quoi couper.")],
    md=['real-40', 'actor-zoe'],
    faq=[("Peut-on montrer l'interface de mon appli ?", "Oui : importez vos captures d'écran, l'éditeur les insère dans la vidéo entre deux plans de l'acteur."),
         ("Ça marche pour du B2B ?", "Oui. Pour un logiciel B2B, un objectif démo ou essai gratuit et un ciblage par métier donnent de bons résultats.")],
    rel=['editeur-video', 'espion-meta-ads', 'b2b-leads']),

  'franchises-reseaux': dict(
    meta=("Growthity pour les franchises et les réseaux", "Une créa commune, une campagne locale par point de vente : la marque respectée partout et les résultats de tout le réseau au même endroit."),
    pill='Franchises & réseaux', h=('Une marque,', 'une campagne par ville.'),
    lede="Franchises, réseaux d'agences, enseignes multi-sites : Growthity décline une créa commune pour chaque point de vente, avec sa ville, sa zone et son budget, dans un seul espace.",
    scen=scen('Réseau', 18400, "Maison Verte, c'est 20 jardiniers franchisés en France. Je veux une campagne locale pour chacun.",
              "On crée une vidéo commune, puis une campagne par franchisé, chacune ciblée sur sa ville.", None,
              "Voici 3 profils :", [['ugc-pac-awa', 'Awa'], ['ugc-scierie', 'Sofia'], ['real-12', 'Hugo']],
              "Awa, dans un jardin.", "Génération de la vidéo 9:16, puis 20 versions avec la ville de chaque franchisé.",
              dict(video='ugc-pac-awa', words=['Votre jardin', 'entretenu', "<em>toute l'année</em>"]),
              "Publie : 20 campagnes, une par agence sur son département, 15 € par jour chacune.", "20 campagnes créées. Aperçu de celle de Nantes :",
              dict(aud=['20 départements', 'Un par agence', 'Tous genres', '15 € / jour / agence', 'Leads'], brand='Maison Verte', site='maisonverte.fr', logo='nord', video='ugc-pac-awa',
                   text="Votre jardin entretenu toute l'année, sans y penser. Votre jardinier Maison Verte à Nantes vous répond sous 24 h 🌿", headline='Devis gratuit · Maison Verte Nantes', cta='Demander un devis',
                   m=[['Impressions', 31800], ['Clics', 870], ['Devis', 64]])),
    hooks=[('Proximité', 'Votre jardinier à Nantes, à 10 minutes de chez vous.', "Le nom de la ville rend un réseau national aussi proche qu'un artisan du coin."),
           ('Confiance', 'Le réseau qui entretient des centaines de jardins près de chez vous.', "La force du réseau rassure, la proximité convainc."),
           ('Saison', 'Le printemps arrive : votre jardin est prêt ?', "Les rendez-vous de saison créent une urgence naturelle, ville par ville.")],
    pains=('Au cas par cas', ["Chaque franchisé bricole ses propres pubs", "Une image de marque qui part dans tous les sens", "Des budgets dispersés, impossibles à comparer", "Le siège ne voit pas ce qui marche"],
           'Un seul espace', ["Une créa commune, déclinée par ville", "La marque respectée partout", "Une campagne par point de vente, sur sa zone", "Les résultats de tout le réseau, comparés"]),
    uses=['Franchises', "Réseaux d'agences", 'Enseignes multi-sites', 'Coopératives', 'Concessionnaires', "Groupements d'artisans"],
    bento=[('store', 'green', 'Une campagne par point de vente', "Même créa, même marque, une zone et un budget propres à chaque adresse."),
           ('shield', 'indigo', 'Votre charte respectée', "Couleurs, ton et messages validés par le siège, déclinés pour chaque ville."),
           ('pin', 'orange', 'Le local dans la pub', "Le nom de la ville, l'adresse ou le prénom du franchisé dans chaque version."),
           ('chart', 'blue', "Tout le réseau d'un coup d'œil", "Comparez les résultats des points de vente et repérez les meilleures pratiques."),
           ('users', 'pink', 'Siège et franchisés', "Rôles admin et éditeur : chacun voit et gère ce qui le concerne."),
           ('euro', 'slate', '0 % de commission', "Chaque campagne est payée sur le compte Meta choisi, sans frais sur le budget.")],
    md=['ugc-pac-awa', 'ugc-scierie'],
    faq=[("Chaque franchisé peut-il gérer sa campagne ?", "Oui : invitez-le dans l'espace avec le rôle qui convient. Le siège garde la main sur la marque."),
         ("Peut-on garder des budgets séparés ?", "Oui : chaque campagne a son budget, sa zone et ses résultats, comparables dans un seul tableau.")],
    rel=['agences', 'commerce-local', 'pilotage-ia']),

  'lancement-produit': dict(
    meta=("Lancer un produit avec Growthity", "Vidéo, visuels et carrousel prêts le jour J, plusieurs angles testés dès le départ et la créa gagnante repérée en quelques jours."),
    pill='Lancer un produit', h=('Un lancement', 'qui fait du bruit.'),
    lede="Nouveau produit, nouvelle collection, édition limitée : Growthity prépare toutes vos créas pour le jour J, teste plusieurs angles en même temps et vous dit lequel pousser.",
    scen=scen('Lancement', 6900, "On sort une nouvelle collection de cartes illustrées. Je veux la faire connaître avant les fêtes.",
              "Pour un lancement : une découverte face caméra, ton coup de cœur.", None,
              "Voici 3 profils :", [['real-19', 'Julie'], ['ugc-femme', 'Léa'], ['real-05', 'Clara']],
              "Julie, effet coup de cœur.", "Génération : vidéo 9:16 de découverte, sous-titres inclus.",
              dict(video='real-19', words=['La collection', '<em>est arrivée</em>', '✨']),
              "Publie : France, 25-50 ans, 35 € par jour pendant le lancement, objectif ventes.", "C'est en ligne. Aperçu de ta pub :",
              dict(aud=['France', '25–50 ans', 'Tous genres', '35 € / jour', 'Ventes'], brand='Papeterie Lou', site='papeterielou.fr', logo='lou', video='real-19',
                   text="Notre nouvelle collection de cartes est là : illustrée à la main, imprimée en France. Les premières séries partent vite ✨", headline='Nouvelle collection · Cartes de vœux', cta='Découvrir',
                   m=[['Impressions', 24500], ['Clics', 690], ['Ventes', 57]])),
    hooks=[('Nouveauté', 'Ça y est, elle est enfin là.', "Le ton de l'annonce entre amis crée plus d'envie qu'un communiqué."),
           ('Coulisses', 'On a mis 6 mois à la créer, voici pourquoi.', "Raconter la fabrication donne de la valeur avant même le prix."),
           ('Rareté', 'Première série limitée.', "Un stock limité au lancement pousse à commander tout de suite.")],
    pains=('6 semaines', ["Organiser un shooting avant chaque lancement", "Une seule vidéo pour toute la campagne", "Des retours trop tardifs pour corriger le tir", "Un lancement qui s'essouffle en quelques jours"],
           'Le jour J', ["Vidéo, visuels et carrousel prêts le jour J", "Plusieurs angles testés dès le premier jour", "Les meilleurs messages repérés en quelques jours", "De nouvelles versions pour garder l'élan"]),
    uses=['Nouvelle collection', 'Nouveau produit', 'Édition limitée', 'Précommande', 'Ouverture de boutique', 'Nouvelle offre', 'Événement', 'Saison des fêtes'],
    bento=[('rocket', 'pink', 'Prêt le jour J', "Vidéo, visuels et carrousel de la nouveauté générés à partir de vos premières photos."),
           ('layers', 'orange', 'Plusieurs angles dès le départ', "Découverte, coulisses, rareté : testez-les en même temps pour trouver le bon."),
           ('copy', 'indigo', 'Toute la collection', "Un carrousel ou un lot de créas pour présenter chaque pièce."),
           ('trend', 'green', 'Accélérez ce qui marche', "Le pilotage IA repère la créa gagnante en quelques jours et vous dit où mettre le budget."),
           ('search', 'blue', 'Ce que font les autres', "Repérez les lancements de votre secteur qui ont le mieux marché."),
           ('refresh', 'slate', "Gardez l'élan", "De nouvelles versions avant que la première pub ne s'essouffle.")],
    md=['real-19', 'img-sneakers.webp'],
    faq=[("Quand faut-il commencer ?", "Préparez vos créas quelques jours avant et publiez le jour J. Les premiers résultats arrivent en quelques jours."),
         ("Je n'ai pas encore de photos pro du produit.", "Une photo nette suffit : le chat la met en scène dans un visuel, un carrousel ou une vidéo.")],
    rel=['creations-catalogue', 'studio-en-lot', 'pilotage-ia']),

  'recrutement': dict(
    meta=("Recruter avec Growthity", "Des annonces vidéo incarnées par vos managers, diffusées sur Facebook et Instagram autour de vos sites, avec des candidatures qualifiées."),
    pill='Recruter', h=('Des candidats,', 'pas seulement des clients.'),
    lede="Sur Facebook et Instagram, vous touchez aussi ceux qui ne regardent pas les sites d'emploi. Growthity crée l'annonce vidéo, la diffuse autour de vos sites et récolte les candidatures.",
    scen=scen('Recrutement', 3880, "Je dois recruter 10 conseillers commerciaux à Lille. Les annonces classiques ne donnent rien.",
              "Sur Meta, on touche aussi les gens qui ne cherchent pas activement. Un manager qui parle de l'équipe, c'est l'angle le plus efficace.", None,
              "Voici 3 profils :", [['actor-thomas', 'Thomas'], ['ugc-homme', 'Marc'], ['actor-claire', 'Claire']],
              "Thomas, ton direct et sympa.", "Génération : vidéo 9:16, sous-titres inclus.",
              dict(video='actor-thomas', words=['On recrute', '<em>10 conseillers</em>', 'à Lille']),
              "Publie : département du Nord, 25 € par jour, formulaire de candidature.", "Campagne de candidatures créée. Aperçu :",
              dict(aud=['Nord (59)', 'Tous âges', 'Tous genres', '25 € / jour', 'Leads'], brand='Groupe Horizon', site='groupe-horizon.fr', logo='horizon', color='#0F172A', video='actor-thomas',
                   text="On agrandit l'équipe de Lille : 10 postes de conseillers, formation assurée, CDI. Postulez en 2 minutes, sans CV 👇", headline='Conseiller commercial · CDI · Lille', cta='Postuler',
                   m=[['Impressions', 15600], ['Clics', 488], ['Candidatures', 43]])),
    hooks=[('Le manager', "Je vous présente l'équipe que vous allez rejoindre.", "Un visage et une équipe rassurent plus qu'une fiche de poste."),
           ('Sans CV', 'Postulez en 2 minutes, sans CV.', "Moins de friction, c'est plus de candidatures de ceux qui ne cherchent pas activement."),
           ('Le quotidien', 'Une journée type chez nous, sans filtre.', "Montrer le vrai quotidien attire les bons profils et décourage les autres.")],
    pains=('Jobboards', ["Payer des annonces sur les sites d'emploi", "Attendre que les candidats viennent à vous", "Des CV qui ne correspondent pas", "Des cabinets payés au pourcentage du salaire"],
           'Candidats', ["Toucher aussi ceux qui ne cherchent pas", "Une vidéo qui donne envie de rejoindre l'équipe", "Un formulaire court avec vos questions de tri", "Chaque candidature reliée à sa pub"]),
    uses=['Commerce & vente', 'Restauration', 'Bâtiment', 'Transport & logistique', 'Aide à domicile', 'Industrie', 'Hôtellerie', 'Saisonniers'],
    bento=[('users', 'slate', "Vos équipes à l'écran", "Un manager ou un collaborateur qui présente le poste, en vidéo, sans tournage."),
           ('target', 'green', 'Candidatures qualifiées', "Formulaire Meta avec vos questions : permis, disponibilités, expérience."),
           ('pin', 'orange', 'Autour de vos sites', "Touchez les candidats qui vivent près de votre agence, magasin ou chantier."),
           ('bolt', 'pink', 'Plusieurs postes en une fois', "Une vidéo par poste ou par site, produite en lot."),
           ('chart', 'blue', 'Coût par candidature', "Le pilotage IA vous dit quelle annonce ramène les meilleurs candidats au meilleur prix."),
           ('lock', 'indigo', 'Vos candidats, vos données', "Les candidatures arrivent dans votre espace, rien n'est revendu.")],
    md=['actor-thomas', 'ugc-homme'],
    faq=[("Les candidatures sont-elles triées ?", "Oui : le chat crée le formulaire Meta avec vos questions (permis, disponibilités, expérience) et une réponse disqualifiante passe la candidature en « Non qualifié »."),
         ("Peut-on recruter sur Instagram aussi ?", "Oui, les campagnes sont diffusées sur Facebook et Instagram, là où sont aussi les candidats qui ne consultent pas les sites d'emploi.")],
    rel=['leads-ventes', 'acteurs-ugc', 'b2b-leads']),
}


def build_sector(b, slug, d):
    sec, head, stack = b.section, b.head, b.stack
    plain, grad = d['h']
    body = stack(
        b.hero_center(slug, ('Solutions', d['pill']), plain, grad, d['lede'], demo=b.chat_custom([d['scen']])),
        sec(stack(head('Les angles qui marchent', 'Des accroches pensées', 'pour votre secteur.',
                       "Des exemples d'angles que le chat vous propose, et pourquoi ils fonctionnent sur Meta."), b.hooks(d['hooks'])), cls='night'),
        sec(stack(head('Pourquoi Growthity', 'Moins de temps,', 'plus de résultats.'), b.pains(*d['pains']))),
        sec(stack(head('Ce que vous obtenez', 'Tout ce qu\'il faut', 'pour vendre sur Meta.'), b.features(d['bento'], md=d['md'])), cls='tint'),
        sec(stack(head('Pour qui', 'Toutes les activités', 'du secteur.'), b.uses([(u, None) for u in d['uses']]))),
        stack(b.section(b.faq2(d['faq'])),
              b.section(stack(head('À découvrir aussi', 'Allez plus loin', 'avec Growthity.'), b.related(d['rel'])), cls='tint', style='padding-top:60px'),
              b.final()))
    return (d['meta'][0], d['meta'][1], body)
